// Builds the extension frontend into dist/frontend (readable, unminified ES modules).
//
//   node scripts/build-frontend.ts                  dev build (EBS via local dev proxy)
//   EBS_URL=https://ebs.example.com node scripts/build-frontend.ts --zip
//                                                   Hosted Test / review build + zip
import { spawnSync } from "node:child_process";
import { cpSync, existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

const ROOT = resolve(import.meta.dirname, "..");
const SRC = join(ROOT, "frontend/src");
const OUT = join(ROOT, "dist/frontend");
const zip = process.argv.includes("--zip");
const ebsUrl = (process.env.EBS_URL ?? "https://localhost:8080/ebs").replace(/\/$/, "");

if (zip && (!ebsUrl.startsWith("https://") || /localhost|127\.0\.0\.1/.test(ebsUrl))) {
  console.error("A Hosted Test / review zip needs EBS_URL set to the public HTTPS address of the EBS.");
  process.exit(1);
}

rmSync(OUT, { recursive: true, force: true });
mkdirSync(OUT, { recursive: true });

const tsc = spawnSync(process.execPath, [join(ROOT, "node_modules/typescript/bin/tsc"), "-p", join(ROOT, "frontend/tsconfig.json")], {
  stdio: "inherit",
});
if (tsc.status !== 0) process.exit(tsc.status ?? 1);

for (const f of readdirSync(SRC)) {
  if (f.endsWith(".html") || f.endsWith(".css")) cpSync(join(SRC, f), join(OUT, f));
}
writeFileSync(
  join(OUT, "env.js"),
  `// Generated by scripts/build-frontend.ts\nexport const EBS_BASE = ${JSON.stringify(ebsUrl)};\n`,
);

// Sanity checks mirroring Twitch review rules.
for (const f of readdirSync(OUT).filter((f) => f.endsWith(".html"))) {
  const html = readFileSync(join(OUT, f), "utf8");
  const scripts = [...html.matchAll(/<script[^>]*src="([^"]+)"/g)].map((m) => m[1]!);
  if (scripts[0] !== "https://extension-files.twitch.tv/helper/v1/twitch-ext.min.js") throw new Error(`${f}: helper must be the first script`);
  const remote = scripts.slice(1).filter((s) => /^https?:/.test(s));
  if (remote.length) throw new Error(`${f}: remote scripts are not allowed: ${remote.join(", ")}`);
}

console.log(`Built frontend -> ${OUT} (EBS_BASE=${ebsUrl})`);

if (zip) {
  const version = JSON.parse(readFileSync(join(ROOT, "package.json"), "utf8")).version ?? "0.0.0";
  const zipPath = join(ROOT, `dist/frontend-${version}.zip`);
  rmSync(zipPath, { force: true });
  // No `zip` binary on this machine: use the venv's Python. Files go at the zip root.
  const python = existsSync(join(ROOT, ".venv/bin/python")) ? join(ROOT, ".venv/bin/python") : "python3";
  const code = [
    "import os, sys, zipfile",
    "src, out = sys.argv[1], sys.argv[2]",
    "with zipfile.ZipFile(out, 'w', zipfile.ZIP_DEFLATED) as z:",
    "    for d, _, files in os.walk(src):",
    "        for f in sorted(files):",
    "            p = os.path.join(d, f)",
    "            z.write(p, os.path.relpath(p, src))",
  ].join("\n");
  const r = spawnSync(python, ["-I", "-c", code, OUT, zipPath], { stdio: "inherit" });
  if (r.status !== 0) process.exit(r.status ?? 1);
  console.log(`Zipped -> ${zipPath} (upload under Version > Files > Upload Version Assets)`);
}
