#!/usr/bin/env bash
# Runs the whole extension locally against mocks (no Twitch credentials needed):
#   Twitch CLI mock API  http://localhost:8090   (Helix + OAuth)
#   mock DDD API         http://127.0.0.1:8095   (replays real DDD responses you captured with
#                                                 scripts/capture-ddd-fixtures.ts and your own key)
#   EBS                  http://127.0.0.1:8081
#   frontend + /ebs      https://localhost:8080  (harness: /harness/panel.html, /harness/config.html)
#
# Config is generated into .env.mock on first run. Ctrl+C stops everything.
#   bash scripts/local-stack.sh
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
VENV="$ROOT/.venv"
export PATH="$VENV/bin:$PATH"
cd "$ROOT"

if [[ ! -f ebs/test/fixtures/ddd/topics.json ]] || [[ -n "$(find ebs/test/fixtures/ddd/topics.json -mtime +29)" ]]; then
  echo "DDD fixtures missing or older than 30 days. Capture them (needs DDD_API_KEY in .env):"
  echo "  node --env-file=.env scripts/capture-ddd-fixtures.ts"
  exit 1
fi

pids=()
cleanup() { for p in "${pids[@]}"; do kill "$p" 2>/dev/null || true; done; }
trap cleanup EXIT INT TERM

wait_for() { for _ in $(seq 1 60); do curl -sk "$1" >/dev/null 2>&1 && return 0; sleep 0.5; done; echo "timed out waiting for $1"; return 1; }

mkdir -p "$ROOT/data"
STATE="${XDG_STATE_HOME:-$HOME/.local/state}/twitch-content-warnings/twitch-cli"
if [[ ! -f "$STATE/eventCache.db" ]]; then
  twitch mock-api generate -c 5 >/dev/null 2>&1
fi
twitch mock-api start -p 8090 > "$ROOT/data/mock-api.log" 2>&1 &
pids+=($!)
wait_for http://localhost:8090/units/clients

if [[ ! -f .env.mock ]]; then
  read -r CID CSECRET < <(curl -s http://localhost:8090/units/clients | "$VENV/bin/python" -c \
    "import json,sys; c=json.load(sys.stdin)['data'][0]; print(c['ID'], c['Secret'])")
  OWNER=$(curl -s http://localhost:8090/units/users | "$VENV/bin/python" -c "import json,sys; print(json.load(sys.stdin)['data'][0]['id'])")
  cat > .env.mock <<EOF
# Generated by scripts/local-stack.sh for local runs against mocks. Not real credentials.
NODE_ENV=development
TWITCH_EXT_CLIENT_ID=$CID
TWITCH_EXT_CLIENT_SECRET=$CSECRET
TWITCH_EXT_SECRET=$(openssl rand -base64 32)
TWITCH_EXT_OWNER_ID=$OWNER
TWITCH_API_BASE=http://localhost:8090/mock
TWITCH_TOKEN_URL=http://localhost:8090/auth/token
DDD_API_KEY=mock-key
DDD_API_BASE=http://127.0.0.1:8095
DATABASE_PATH=./data/mock-cache.sqlite
DATABASE_VFS=unix-dotfile
ALLOWED_ORIGINS=https://localhost:8080
EVENTSUB_CALLBACK_URL=https://localhost:8080/ebs/eventsub
EVENTSUB_SECRET=$(openssl rand -hex 16)
EOF
  echo "Wrote .env.mock"
fi

node scripts/mock-ddd.ts > data/mock-ddd.log 2>&1 &
pids+=($!)
wait_for http://127.0.0.1:8095/ || { cat data/mock-ddd.log; exit 1; }
node --env-file=.env.mock ebs/src/server.ts > data/ebs.log 2>&1 &
pids+=($!)
wait_for http://127.0.0.1:8081/health
node --env-file=.env.mock scripts/dev-frontend.ts > data/dev-frontend.log 2>&1 &
pids+=($!)
wait_for https://localhost:8080/panel.html

CH=$(grep TWITCH_EXT_OWNER_ID .env.mock | cut -d= -f2)
cat <<EOF

Local stack is up (logs in data/*.log):
  Viewer panel:   https://localhost:8080/harness/panel.html?channel=$CH
  Broadcaster:    https://localhost:8080/harness/config.html?channel=$CH&role=broadcaster
  Fire a category change (EventSub -> EBS):
    twitch event trigger channel.update -v 2 -t $CH -G 46068 -n "Just Developing" \\
      -F http://127.0.0.1:8081/eventsub -s \$(grep EVENTSUB_SECRET .env.mock | cut -d= -f2)

Ctrl+C to stop.
EOF
wait
